version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordcloud1
      - wordcloud2
      - wordcloud3
    networks:
      - wordcloud_net

  wordcloud1:
    build: .
    expose:
      - "5000"
    environment:
      - INSTANCE_NAME=wordcloud1
    networks:
      - wordcloud_net
    volumes:
      - wordcloud_data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  wordcloud2:
    build: .
    expose:
      - "5000"
    environment:
      - INSTANCE_NAME=wordcloud2
    networks:
      - wordcloud_net
    volumes:
      - wordcloud_data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  wordcloud3:
    build: .
    expose:
      - "5000"
    environment:
      - INSTANCE_NAME=wordcloud3
    networks:
      - wordcloud_net
    volumes:
      - wordcloud_data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:alpine
    networks:
      - wordcloud_net
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  wordcloud_net:
    driver: bridge

volumes:
  wordcloud_data:
  redis_data: